site_name: 2023-Yatcpu-Fall-Docs
site_author: Tokisakix
copyright: Copyright Â© 2023 Tokisakix

nav:
- å‰è¨€: index.md
- å¦‚ä½•ä¸€é”®ç¯å¢ƒé…ç½®: env.md
- å¦‚ä½•ä¸€é”®çƒ§æ¿: board.md
- æœ€ç»ˆéªŒæ”¶: test.md
- better-tut/intro.md
- ç†è®ºçŸ¥è¯†åŸºç¡€:
  - better-tut/theory/cpu-arch.md
  - better-tut/theory/riscv-isa.md
  - better-tut/theory/interrupt-and-exception.md
- åŸºç¡€å·¥ç¨‹çŸ¥è¯†ä¸æŠ€èƒ½:
  - better-tut/practice/envvar-and-cmd.md
  - better-tut/practice/scala-and-chisel.md
- å®éªŒ:
  - better-tut/labs/lab1/lab1-single-cycle-cpu.md
  - better-tut/labs/lab2/lab2-interrupt.md
  - better-tut/labs/lab3/lab3-pipelined-cpu.md



theme:
  name: material
  features:
    - content.tabs.link
    - navigation.expand


markdown_extensions:
  - toc:
      permalink: "ğŸš"
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true